/// <reference types="cypress" />

/**
 * GAMES
 * Different chess games
 * (run on analysis board)
 */

const { INPUT_SELECTOR } = require('../constants');

const ARROW_SELECTOR = 'img.chessBoardArrow';
const E2E4_ARROW_SELECTOR = 'chess-board .arrows [data-arrow="e2e4"]';
const SQUARE_SELECTOR = 'chess-board [class^="highlight square-"][style*="background-color: rgb(235, 97, 80)"]';

context('Chess games', () => {
  beforeEach(() => {
    cy.visit('https://www.chess.com/analysis')
    cy.wait(10000)
    cy.fixture('positions').as('positions')
  });

  it('Tal-Spassky', function() {
    cy
      .makeMove('c4')
      .makeMove('Nf6')
      .makeMove('Nc3')
      .makeMove('e6')
      .makeMove('d4')
      .makeMove('c5')
      .makeMove('d5')
      .makeMove('exd5')
      .makeMove('cxd5')
      .makeMove('g6')
      .makeMove('Nf3')
      .makeMove('Bg7')
      .makeMove('Bf4')
      .makeMove('d6')
      .makeMove('h3')
      .makeMove('O-O')
      .makeMove('e3')
      .makeMove('Ne8')
      .makeMove('Be2')
      .makeMove('Nd7')
      .makeMove('O-O')
      .makeMove('Ne5')
      .makeMove('Bxe5')
      .makeMove('dxe5')
      .makeMove('Nd2')
      .makeMove('f5')
      .makeMove('Qb3')
      .makeMove('Nd6')
      .makeMove('Nc4')
      .makeMove('e4')
      .makeMove('Nb5')
      .makeMove('Nxb5')
      .makeMove('Qxb5')
      .makeMove('b6')
      .makeMove('d6')
      .makeMove('Bd7')
      .makeMove('Qb3')
      .makeMove('b5')
      .makeMove('Nb6+')
      .makeMove('c4')
      .makeMove('Bxc4+')
      .makeMove('bxc4')
      .makeMove('Qxc4+')
      .makeMove('Rf7')
      .makeMove('Nxa8')
      .makeMove('Qxa8')
      .makeMove('Qb3')
      .makeMove('Be5')
      .makeMove('Rac1')
      .makeMove('Kg7')
      .makeMove('Rfd1')
      .makeMove('a5')
      .makeMove('Rc7')
      .makeMove('Qe8')
      .makeMove('Qd5')
      .makeMove('a4')
      .makeMove('b4')
      .makeMove('axb3')
      .makeMove('axb3')
      .makeMove('Bf6')
      .makeMove('Rb7')
      .makeMove('Qe5')
      .makeMove('Qc4')
      .makeMove('f4')
      .makeMove('exf4')
      .makeMove('Qxf4')
      .makeMove('g3')
      .makeMove('Qf3')
      .makeMove('Qd5')
      .makeMove('Bc3')
      .makeMove('Rf1')
      .makeMove('Kh6')
      .makeMove('Qd1')
      .makeMove('Qf6')
      .makeMove('Qe2')
      .makeMove('Bd4')
      .makeMove('Rb4')
      .makeMove('e3')
      .makeMove('Qd3')
      .makeMove('Qxf2+')
      .makeMove('Rxf2')
      .makeMove('exf2+')
      .makeMove('Kh2')
      .makeMove('f1=N+')
      .makeMove('Qxf1')
      .makeMove('Rxf1')
      .makeMove('Rxd4')
      .makeMove('Rf2+')
      .makeMove('Kg1')
      .makeMove('Rf3')
      .fenEquals(this.positions['tal-spassky'].positions.end)
  });

  it('Opera night', function() {
    cy
      .makeMove('e4')
      .makeMove('e5')
      .makeMove('Nf3')
      .makeMove('d6')
      .makeMove('d4')
      .makeMove('Bg4')
      .makeMove('dxe5')
      .makeMove('Bxf3')
      .makeMove('Qxf3')
      .makeMove('dxe5')
      .makeMove('Bc4')
      .makeMove('Nf6')
      .makeMove('Qb3')
      .makeMove('Qe7')
      .makeMove('Nc3')
      .makeMove('c6')
      .makeMove('Bg5')
      .makeMove('b5')
      .makeMove('Nxb5')
      .makeMove('cxb5')
      .makeMove('Bxb5+')
      .makeMove('Nbd7')
      .makeMove('O-O-O')
      .makeMove('Rd8')
      .makeMove('Rxd7')
      .makeMove('Rxd7')
      .makeMove('Rd1')
      .makeMove('Qe6')
      .makeMove('Bxd7+')
      .makeMove('Nxd7')
      .makeMove('Qb8+')
      .makeMove('Nxb8')
      .makeMove('Rd8#')
      .fenEquals(this.positions['opera-night'].positions.end)
  });
});
